
stages:
  perpare_data:
    cmd: python src/stage_01_preparation_data.py
    deps:
    - src/stage_01_preparation_data.py
    - data/data.xml
    - src/utils
    outs:
    - artifacts/prepared

  featurize_data:
    cmd: python src/stage_02_featurization.py
    deps:
    - src/stage_02_featurization.py
    - artifacts/prepared
    - src/utils
    outs:
    - artifacts/features

  training:
    cmd: python src/stage_03_training.py
    deps:
    - src/stage_03_training.py
    - artifacts/features/train.pkl
    - src/utils
    outs:
    - artifacts/model
  
  evaluate:
    cmd: python src/stage_04_eval.py
    deps:
    - src/stage_04_eval.py
    - src/utils
    - artifacts/features/test.pkl
    - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: false_positive
          y: true_positive
